version: 2.1
jobs:
  staging deployment:
    docker:
      - image: circleci/python:3.8
    working _directory: ~/app
    # working_directory:
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Install Dependencies
          command:  |
            pip install -r requirements.txt
      - run:
          name: Run Tests
          command:  |
            pytest tests/test_app.py
      - run:
          name: Build Docker Image
          command:  |
            docker build -t mlops_demo .
      - run:
          name: Tag Docker Image
          command:  |
            docker tag mlops_demo:latest 959699564310.dkr.ecr.us-east-2.amazonaws.com/mlops_demo:latest
      - run:
          name: Deploy to Staging
          command:  |
            sudo pip install awscli
            eval $(aws ecr get-login --no-include-email --region us-east-2)
            aws ecr get-login --no-include-email --region us-east-2
            docker push 959699564310.dkr.ecr.us-east-2.amazonaws.com/mlops_demo:latest
  
  workflows:
    version: 2
    build-and-deploy:
      jobs:
        - staging_deployment:
            filters:
              branches:
                only:
                  - main 